version: '3.9'

services:
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://myuser:password@database:5432/item_database
    depends_on:
      - database
  
  database:
    container_name: database
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=myuser
      - POSTGRES_DB=item_database
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}