version: '3.9'

services:
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build: ./docker/pythonapp
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@database:5432/dvdrental
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: database
    build: ./docker/database
    ports:
      - "5432:5432"
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dvdrental
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}